<!DOCTYPE html>
<?php
    $controller = $this->dispatcher->getControllerName(); 
    $arrInfos = explode('//', $objInit->getFooterLeftInfos());
?>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link rel="stylesheet" href="<?= $this->url->getBaseUri() ?>/flexslider/flexslider.css" type="text/css" media="screen" />
        <link type="text/css" rel="stylesheet" href="<?= $this->url->getBaseUri() ?>materialize/css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?= $this->url->getBaseUri() ?>css/institucional.css"  media="screen,projection"/>

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>
            <?=$objInit->getTitle();?>
        </title>
        <script type="text/javascript" src="<?= $this->url->getBaseUri() ?>js/jquery-3.2.1.min.js"></script>
        <!-- FlexSlider -->
        <script defer src="<?= $this->url->getBaseUri() ?>flexslider/jquery.flexslider.js"></script>
        <script type="text/javascript" src="<?= $this->url->getBaseUri() ?>materialize/js/materialize.min.js"></script>
        <script type="text/javascript" src="<?= $this->url->getBaseUri() ?>js/institucional.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                var dados = jQuery.parseJSON('<?=$objInit->getFooterRightIcons()?>');
                var html = '<h5 class="white-text icons" style="margin: 5px">'+dados.title_footer_right+'</h5>';
                html += '<ul class="ul-midias" style="display: flex;">';
                for(var i in dados.icons){
                    html += '<li style="margin: 5px;">\
                                <a href="'+dados.icons[i].link+'">\
                                    <i class="material-icons" target="_blank">\
                                        <img src="<?=$this->url->getBaseUri()?>'+dados.icons[i].icon_path+'" class="icons"></i></a>\
                            </li>';
                }
                html += '</ul>';
                $('#footer-right').append(html);
            })
        </script>
    </head>
    <body>
        <header style="height: 120px !important;">
            <!-- nav -->
            <div class="navbar-fixed">
                <nav>
                    <div class="container">
                        <div class="nav-wrapper">
                            <a href="#!" class="brand-logo"><img src="<?=$this->url->getBaseUri().$objInit->getLogoPath()?>" class="logo responsive-img"></a>
                            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                            <ul class="hide-on-med-and-down right">
                                <li class="<?= $controller == 'index' ? 'active' : '' ?>"><a href="<?= $this->url->getBaseUri() ?>"><i class="material-icons">home</i></a></li>
                                <li class="<?= $controller == 'historia' ? 'active' : '' ?>"><a href="<?= $this->url->getBaseUri() ?>historia/"><span>HISTORIA</span></a></li>
                                <li class="<?= $controller == 'institucional' ? 'active' : '' ?>"><a href="<?= $this->url->getBaseUri() ?>institucional/"><span>INSTITUCIONAL</span></a></li>
                                <li class="<?= $controller == 'servicos' ? 'active' : '' ?>"><a href="<?= $this->url->getBaseUri() ?>servicos/"><span>SERVIÇOS</span></a></li>
                                <li class="<?= $controller == 'contato' ? 'active' : '' ?>"><a href="<?= $this->url->getBaseUri() ?>contato/"><span>CONTATO</span></a></li>
                            </ul>
                            <!-- nav mobile -->
                            <ul class="side-nav" id="mobile-demo">
                                <li class="<?= $controller == 'historia' ? 'active' : '' ?>"><a href="<?= $this->url->getBaseUri() ?>historia/"><span>HISTORIA</span></a></li>
                                <li class="<?= $controller == 'servicos' ? 'active' : '' ?>"><a href="<?= $this->url->getBaseUri() ?>servicos/"><span>SERVIÇOS<span></a></li>
                                <li class="<?= $controller == 'contato' ? 'active' : '' ?>"><a href="<?= $this->url->getBaseUri() ?>contato/"><span>CONTATO</span></a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <main>
            <?php echo $this->getContent(); ?>
        </main>

        <footer class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="white-text"><?=$objInit->getFooterLeftTitle()?></h5>
                        <?php foreach ($arrInfos as $info) { ?>
                            <p class="grey-text text-lighten-4">
                                <?=$info?>
                            </p>
                        <?php } ?>
                    </div>
                    <div class="col l4 offset-l2 s12" id="footer-right">
                        
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    © 2017 <a href="http://www.paulocesarweb.com.br" target="__blank">Paulo Cesar Web</a>
                </div>
            </div>
        </footer>
    </body>
</html>
