<div class="container">
    <div class="row">
        <div class="col s12">
            <h5 title="Contato"><u>Formulário de Contato</u></h5>
        </div>
    </div>
    <div class="row" id="contato" style="display: none">
        <h3 class="center light">Contato</h3>
        <div class="input-field col s12 m6 offset-m3">
            <i class="material-icons prefix icon">person_outline</i>
            <input autocomplete="off" id="nome" type="text" class="input-padrao" name="nome">
            <label class="label-padrao" for="nome">Nome</label>
        </div>
        <div class="input-field col s12 m6 offset-m3">
            <i class="material-icons prefix icon">mail_outline</i>
            <input autocomplete="off" id="email" name="email" class="input-padrao" type="text">
            <label class="label-padrao" for="email">Email</label>
        </div>
        <div class="input-field col s12 m6 offset-m3">
            <i class="material-icons prefix icon">phone</i>
            <input autocomplete="off" id="telefone" class="input-padrao" name="telefone" type="text">
            <label class="label-padrao" for="telefone">Telefone</label>
        </div>
        <div class="input-field col s12 m6 offset-m3">
            <i class="material-icons prefix icon">chat_bubble_outline</i>
            <textarea autocomplete="off" id="mensagem" name="mensagem" class="materialize-textarea input-padrao"></textarea>
            <label class="label-padrao" for="mensagem">Deixe sua mensagem</label>
        </div>
        <div class="input-field col s12 center">
            <span class="gh-ico" aria-hidden="true"></span>
            <button type="button" class="btn btn-padrao" name="enviar-contato">Enviar</button>
        </div>
    </div>
</div>
<script>
    $("#contato").toggle("slow");
</script>
