<div class="row">
    <div class="col s6">
        
        <div class="flexslider">
          <ul class="slides">
            <li>
              <img src="<?=$this->url->getBaseUri()?>img/history_slider/img1.jpg" />
            </li>
            <li>
              <img src="slide2.jpg" />
            </li>
            <li>
              <img src="slide3.jpg" />
            </li>
            <li>
              <img src="slide4.jpg" />
            </li>
          </ul>
        </div>
    </div>
</div>